### ISSUE TITLE
Bot doesn't answer

### ISSUE THREAD

**Issue by iandark** [Vinayak-09/telegrambot-for-instagram#3]
Hi friend!
Thanks for your project!

Something is wrong when i repeat your steps. But bot doesn't answer in telegram.
I create the bot, made my repository with the bot's token api and I made a successfully deploy with heroku.

What mistake i made?

Thanks for your attention!

**Comment by Vinayak-09** [comment]
Instagram changed settings that if you want to check someones profile or photo with link USER must have to be signed in first.
So we first need to sign in to Instagram.
Check out updated code.
